### PR TITLE
Simple mod to function perigee-passage to draw perigee annotation onl…

### PR DESCRIPTION
**Pull request by Gregg140**
IMPORTANT:  Please DO NOT merge this  until I give the all clear.

Basically this is a one liner change to the acisfp_check.py program which places the code for drawing of the vertical lines for the perigee inside an IF statement.

### CODE REVIEW

**Comment by Gregg140** [comment]
p.s. the Release notes are not complete.

**Comment by richardjedgar** [comment]
Looks good to me; as advertised the only actual code change is enclosing the perigee annotation draw function in an if statement. There are some cosmetic comment format changes, and some updates to the release notes as well, plus the test script is changed.

**Comment by jzuhone** [comment]
I have some nitpicky Python-ish thoughts about it but I don't think it's worth bothering given we want to present tomorrow. looks good to me as well.

**Comment by Gregg140** [comment]
Let me know what they are and I'll put them on a list for future FP 
model work.

Thanks

G

**Comment by jzuhone** [comment]
@Gregg140 do you want this merged now then?

**Comment by Gregg140** [comment]
Nope  let's wait until I get the approval to go with it from the Load 
Review Telecon.

Then it can be merged and tagged as Stable

**Comment by Gregg140** [comment]
Ok this change was approved so would someone would please merge it and 
tag it  "Stable"

Thanks,

Gregg

**Comment by richardjedgar** [comment]
Merging after approval by the NOV0716A load review on 2 Nov 2016. Not sure how to tag, but it should be tagged "Stable" now.

**Pull request merged**
