### PR TITLE
Changed FP Sense message from violation to pref not met; changed Vers…

### PR DESCRIPTION
**Pull request by Gregg140**
…ion to 1.02

 ACIS Ops please review these changes. I've changed the language of a focal plane sensitive obs failing to stay colder than -118.7 from "violation" to "preference not met".
For this small change, I bumped the version to 1.02. A total of 2 files changed.

### CODE REVIEW

**Comment by jzuhone** [comment]
@Gregg140 This looks good--any chance we can run the model with the new change to see what an example page looks like? Maybe put a screenshot of that in here or a link.

**Comment by Gregg140** [comment]
Screenshot of the new Preference Not Met line
prefnotmethtml

**Comment by jzuhone** [comment]
Ok, I notice that the "FP_TEMP status" still says "NOT OK" in red. Should we change that too, considering what we're talking about is the fact that a preference is not met?

**Comment by Gregg140** [comment]
All part of the plan. That's the next change (along with a few others like change the ACIS-S violation temperature etc)

 First I wanted to go through the process from start to finish to  get the procedure down and build a checklist.

**Comment by jzuhone** [comment]
Ok, looks good to me. We should get someone else added to the repo and have them sign off as well.

**Comment by Gregg140** [comment]
That would be Dick, as he already has a Github account ;)

**Comment by richardjedgar** [comment]
which thumb to i use to make that happen?

**Comment by jzuhone** [comment]
@richardjedgar since Github doesn't have "approve" buttons (unlike other similar sites), I think saying "looks good" works. @Gregg140, are you ready for the merge button to be pushed? @richardjedgar could do it if he has the privileges already.

**Comment by richardjedgar** [comment]
Looks fine to me. I don't see any 'merge' button.

**Comment by Gregg140** [comment]
See the "Merge pull request" green button just above the place to write pithy comments?

**Comment by richardjedgar** [comment]
Not seeing that.

screenshot-3

**Comment by jzuhone** [comment]
@richardjedgar I just added you as a collaborator--try refreshing the page and see if the button is there.

**Pull request merged**
